### ISSUE TITLE
Corral reports error from primary compilation step

### ISSUE THREAD

**Issue by btab** [ponylang/corral#110]
On Windows (git bash).

`ponyc -o build/release semver` works fine and results in a 0 exit code

`corral run -- ponyc -o build/release semver` reports...

```
run: ponyc -o build/release semver
  exit: Exited(-1)
  out:
  err:
make: *** [build/release/semver.exe] Error -1
```

```
$ ponyc -v
0.35.0 [release]
Compiled with: LLVM 9.0.1 -- MSVC-19.25.28612.0-x64 1925

$ corral version
version: 0.3.4-e152293
```
